# Generated by Django 5.0.8 on 2025-03-13 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduler', '0002_modulerusermodel_clients_modulerusermodel_mandob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android', models.BooleanField(default=False)),
                ('wep', models.BooleanField(default=False)),
                ('bya3', models.BooleanField(default=False)),
                ('mandob', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=50, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('moduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('usermanager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useremployeemanager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
