# Generated by Django 5.0.8 on 2025-03-13 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployee',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useremployeemanager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='usermanager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeemanager', to=settings.AUTH_USER_MODEL),
        ),
    ]
