# Generated by Django 5.0.8 on 2025-03-13 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_useremployee_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useremployee',
            name='rqmqume',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='useremployee',
            name='time_finshe',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
