# Generated by Django 5.0.8 on 2025-03-13 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_useremployee_rqmqume_useremployee_time_finshe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremployee',
            name='to_moduler',
            field=models.IntegerField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 11, 26, 55, 566807)),
        ),
    ]
