# Generated by Django 5.0.8 on 2025-03-13 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_useremployee_to_moduler_alter_useremployee_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployee',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 20, 57, 16, 124068)),
        ),
    ]
