# Generated by Django 5.0.8 on 2025-03-16 20:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_useremployee_end_time'),
        ('moduler', '0003_alter_modulerusermodel_usermanage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployee',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 16, 22, 32, 38, 977909)),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='to_moduler',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='HadorEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_moduler', models.IntegerField(null=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('hador', models.BooleanField(default=True)),
                ('ansraf', models.BooleanField(default=False)),
                ('moduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('useremployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadoremp', to='employee.useremployee')),
                ('usermanager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hadoremployeemanager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
