# Generated by Django 5.0.8 on 2025-03-16 23:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_useremployee_end_time_and_more'),
        ('moduler', '0003_alter_modulerusermodel_usermanage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadoremployee',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 17, 1, 51, 34, 570944)),
        ),
        migrations.CreateModel(
            name='Dof3atEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_moduler', models.IntegerField(null=True)),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('dof3a', models.DecimalField(decimal_places=2, max_digits=7)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('moduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('useremployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dof3atemp', to='employee.useremployee')),
                ('usermanager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dof3atemployeemanager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
