# Generated by Django 5.0.8 on 2025-03-24 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_hadoremployee_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremployee',
            name='bya3',
        ),
        migrations.RemoveField(
            model_name='useremployee',
            name='mandob',
        ),
        migrations.AddField(
            model_name='useremployee',
            name='type_work',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 6, 30, 22, 561876)),
        ),
    ]
