# Generated by Django 5.0.8 on 2025-03-24 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_remove_useremployee_bya3_remove_useremployee_mandob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployee',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 24, 6, 38, 30, 787261)),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='to_moduler',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
