# Generated by Django 5.0.8 on 2025-04-03 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_useremployee_end_time_alter_useremployee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployee',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 3, 8, 27, 52, 740188)),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='to_moduler',
            field=models.IntegerField(null=True),
        ),
    ]
