# Generated by Django 5.0.8 on 2025-04-03 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_useremployee_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployee',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 3, 9, 35, 33, 14666)),
        ),
    ]
