# Generated by Django 5.0.8 on 2025-04-05 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_useremployee_email_alter_useremployee_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useremployee',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 22, 27, 18, 995631)),
        ),
    ]
