# Generated by Django 5.0.8 on 2025-03-07 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandelCartEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pro_cart', models.IntegerField(default=0)),
                ('num_emp_cart', models.IntegerField(default=0)),
                ('event_id', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
                ('android', models.BooleanField(default=False)),
                ('wep', models.BooleanField(default=False)),
                ('desktop', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
