# Generated by Django 5.0.8 on 2025-03-28 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0010_alter_useremployee_end_time_alter_useremployee_user'),
        ('moduler', '0003_alter_modulerusermodel_usermanage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('shop_name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('moduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ccgroupclients', to='moduler.modulerusermodel')),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('is_finished', models.BooleanField(default=False)),
                ('stay', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('Payment', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('barcode', models.ImageField(blank=True, default='profile_pictures/barcode.png', upload_to='images/')),
                ('barcode_id', models.CharField(max_length=13, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientorder', to='clients.client')),
                ('moduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientuser', to=settings.AUTH_USER_MODEL)),
                ('useremployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.useremployee')),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientmanager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientsOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('img', models.CharField(default='', max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type_quantity', models.CharField(max_length=100, null=True)),
                ('dec_product', models.TextField()),
                ('is_finished', models.BooleanField(default=False)),
                ('barcode', models.ImageField(blank=True, default='profile_pictures/barcode.png', upload_to='images/')),
                ('barcode_id', models.CharField(max_length=20, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientorderitems', to='clients.clientsorder')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Dof3atClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('dof3a', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dof3atclientorders', to='clients.client')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dof3atclientorder', to='clients.clientsorder')),
                ('useremployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.useremployee')),
            ],
        ),
        migrations.CreateModel(
            name='GroupClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_group_clients', models.CharField(max_length=30)),
                ('from_moduler', models.IntegerField(null=True)),
                ('moduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel')),
                ('useremployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupclientsemp', to='employee.useremployee')),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupclients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='groupClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.groupclients'),
        ),
    ]
