# Generated by Django 5.0.8 on 2025-03-31 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('moduler', '0003_alter_modulerusermodel_usermanage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsorder',
            name='barcode',
        ),
        migrations.AlterField(
            model_name='client',
            name='groupClient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupClients', to='clients.groupclients'),
        ),
        migrations.AlterField(
            model_name='client',
            name='moduler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupclient', to='moduler.modulerusermodel'),
        ),
        migrations.AlterField(
            model_name='groupclients',
            name='usermanage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupclientsmanager', to=settings.AUTH_USER_MODEL),
        ),
    ]
