# Generated by Django 5.0.8 on 2025-03-31 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_clientsorder_barcode_alter_client_groupclient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsorderdetails',
            name='barcode',
        ),
    ]
