# Generated by Django 5.0.8 on 2025-04-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_clientsorderdetails_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_agel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupclients',
            name='is_agel',
            field=models.BooleanField(default=False),
        ),
    ]
