# Generated by Django 5.0.8 on 2025-04-11 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_is_agel_groupclients_is_agel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dof3atclients',
            name='order',
        ),
    ]
