# Generated by Django 5.0.8 on 2025-03-07 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usermanage_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 8, 0, 2, 20, 546714)),
        ),
        migrations.DeleteModel(
            name='UserEmployee',
        ),
    ]
