# Generated by Django 5.0.8 on 2025-03-13 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usermanage_start_time_delete_useremployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 5, 30, 42, 346835)),
        ),
    ]
