# Generated by Django 5.0.8 on 2025-03-13 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usermanage_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 13, 8, 36, 43, 273976)),
        ),
    ]
