# Generated by Django 5.0.8 on 2025-07-24 01:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_usermanage_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanage',
            name='android',
        ),
        migrations.RemoveField(
            model_name='usermanage',
            name='desktop',
        ),
        migrations.RemoveField(
            model_name='usermanage',
            name='wep',
        ),
        migrations.AlterField(
            model_name='usermanage',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 24, 4, 26, 53, 710033)),
        ),
    ]
