# Generated by Django 5.0.8 on 2025-07-24 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_usermanage_android_remove_usermanage_desktop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 24, 19, 47, 53, 861732)),
        ),
    ]
