# Generated by Django 5.0.8 on 2025-07-26 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_usermanage_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanage',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 26, 17, 18, 59, 945368)),
        ),
    ]
