# Generated by Django 5.0.8 on 2025-03-08 18:25

import django.db.models.deletion
import makhzen.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatgoryProductTypemakhzen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('moduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulercatgoryitemsmakhzen', to='moduler.modulerusermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClosedDaymakhzen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClosedEmpmakhzen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('emp_name', models.CharField(max_length=150)),
                ('close_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closeempitemsmakhzen', to='makhzen.closeddaymakhzen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usermakhzen', to=settings.AUTH_USER_MODEL)),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ordermakhzen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('is_finished', models.BooleanField(default=False)),
                ('stay', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('Payment', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('barcode', models.ImageField(blank=True, default='profile_pictures/barcode.png', upload_to='images/')),
                ('barcode_id', models.CharField(max_length=13, null=True)),
                ('close_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makhzen.closeddaymakhzen')),
                ('close_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closeordersitemsmakhzen', to='makhzen.closedempmakhzen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderusermakhzen', to=settings.AUTH_USER_MODEL)),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordermanagermakhzen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailsmakhzen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('img', models.CharField(default='', max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type_quantity', models.CharField(max_length=100, null=True)),
                ('dec_product', models.TextField()),
                ('is_finished', models.BooleanField(default=False)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitemsmakhzen', to='makhzen.ordermakhzen')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Productsmakhzen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('price_sale', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('type_quantity', models.CharField(max_length=100, null=True)),
                ('product_picture', models.ImageField(default='images/bg_1.jpg', upload_to=makhzen.models.upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_id', models.IntegerField(default=1)),
                ('barcode', models.ImageField(blank=True, upload_to='images/')),
                ('barcode_id', models.CharField(max_length=13, null=True)),
                ('total_sale', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('moduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceBuyProductmakhzen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('quantity_total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_buy', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productitemsmakhzen', to='makhzen.productsmakhzen')),
            ],
        ),
        migrations.AddField(
            model_name='ordermakhzen',
            name='details',
            field=models.ManyToManyField(through='makhzen.OrderDetailsmakhzen', to='makhzen.productsmakhzen'),
        ),
        migrations.AddField(
            model_name='orderdetailsmakhzen',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitemsmakhzen', to='makhzen.productsmakhzen'),
        ),
        migrations.CreateModel(
            name='OrderBackDetailsmakhzen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('img', models.CharField(default='', max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type_quantity', models.CharField(max_length=100, null=True)),
                ('dec_product', models.TextField()),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderbackmanagermakhzen', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orderbackitemsmakhzen', to='makhzen.ordermakhzen')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderbackitemsmakhzen', to='makhzen.productsmakhzen')),
            ],
        ),
    ]
