# Generated by Django 5.0.8 on 2025-04-05 20:28

import django.db.models.deletion
import tsne3.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduler', '0003_alter_modulerusermodel_usermanage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DortTsne3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('moduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dort_tsne3manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dof3atDortTsne3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('dof3a', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dort_tsne3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dof3atdorttsne3', to='tsne3.dorttsne3')),
            ],
        ),
        migrations.CreateModel(
            name='DortTsne3Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('price_sale', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('type_quantity', models.CharField(max_length=100, null=True)),
                ('product_picture', models.ImageField(default='images/bg_1.jpg', upload_to=tsne3.models.upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_id', models.IntegerField(default=1)),
                ('barcode', models.ImageField(blank=True, upload_to='images/')),
                ('barcode_id', models.CharField(max_length=13, null=True)),
                ('total_sale', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('dort_tsne3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antagdorttsne3', to='tsne3.dorttsne3')),
                ('moduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dortproductmanager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DortTsne3PriceBuyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('quantity_total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_buy', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dorttsne3productitems', to='tsne3.dorttsne3products')),
            ],
        ),
        migrations.CreateModel(
            name='Recourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dort_tsne3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recourses', to='tsne3.dorttsne3')),
            ],
        ),
        migrations.CreateModel(
            name='Tklfa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dort_tsne3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tklfa', to='tsne3.dorttsne3')),
            ],
        ),
    ]
