# Generated by Django 5.0.8 on 2025-03-08 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduler', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='moduler',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='modulerorders', to='moduler.modulerusermodel'),
            preserve_default=False,
        ),
    ]
