# Generated by Django 5.0.8 on 2025-03-08 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduler', '0001_initial'),
        ('shop', '0002_order_moduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='moduler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel'),
        ),
    ]
