# Generated by Django 5.0.8 on 2025-04-05 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduler', '0003_alter_modulerusermodel_usermanage'),
        ('shop', '0004_products_usermanage'),
    ]

    operations = [
        migrations.AddField(
            model_name='closedday',
            name='moduler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel'),
        ),
        migrations.AddField(
            model_name='closedemp',
            name='moduler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderbackdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderbackproductitems', to='shop.products'),
        ),
        migrations.AlterField(
            model_name='products',
            name='moduler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsmoduler', to='moduler.modulerusermodel'),
        ),
    ]
