# Generated by Django 5.0.8 on 2025-04-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_closedday_moduler_closedemp_moduler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_order',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
