# Generated by Django 5.0.8 on 2025-04-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_type_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Payment_order',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
