# Generated by Django 5.0.8 on 2025-04-21 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduler', '0003_alter_modulerusermodel_usermanage'),
        ('shop', '0007_order_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbackdetails',
            name='moduler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel'),
            preserve_default=False,
        ),
    ]
