# Generated by Django 5.0.8 on 2025-07-24 16:47

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_orderbackdetails_moduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_picture',
            field=models.ImageField(default='profile_img/store_logo.png', upload_to=shop.models.upload_to),
        ),
    ]
