# Generated by Django 5.0.8 on 2025-03-13 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0005_alter_useremployee_end_time'),
        ('moduler', '0003_alter_modulerusermodel_usermanage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MandobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('is_finished', models.BooleanField(default=False)),
                ('stay', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('Payment', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('barcode', models.ImageField(blank=True, default='profile_pictures/barcode.png', upload_to='images/')),
                ('barcode_id', models.CharField(max_length=13, null=True)),
                ('moduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandobuser', to=settings.AUTH_USER_MODEL)),
                ('useremployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.useremployee')),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandobmanager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MandobOrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('img', models.CharField(default='', max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type_quantity', models.CharField(max_length=100, null=True)),
                ('dec_product', models.TextField()),
                ('is_finished', models.BooleanField(default=False)),
                ('barcode', models.ImageField(blank=True, default='profile_pictures/barcode.png', upload_to='images/')),
                ('barcode_id', models.CharField(max_length=20, null=True)),
                ('mandoborder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mandoborderitems', to='mandob.mandoborder')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MandobProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('price_sale', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('type_quantity', models.CharField(max_length=100, null=True)),
                ('product_picture', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_id', models.IntegerField(default=1)),
                ('barcode_id', models.CharField(max_length=13, null=True)),
                ('total_sale', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('moduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('useremployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.useremployee')),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandobproductmanager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MandobPriceBuyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('quantity_total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total_buy', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandobproductitems', to='mandob.mandobproducts')),
            ],
        ),
    ]
