# Generated by Django 5.0.8 on 2025-04-05 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_useremployee_end_time'),
        ('mandob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mandobproducts',
            name='useremployee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandobproductemp', to='employee.useremployee'),
        ),
    ]
