# Generated by Django 5.0.8 on 2025-04-09 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandob', '0002_alter_mandobproducts_useremployee'),
        ('moduler', '0003_alter_modulerusermodel_usermanage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MandobClosedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('moduler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel')),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mandoborder',
            name='close_day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mandob.mandobclosedday'),
            preserve_default=False,
        ),
    ]
