# Generated by Django 5.0.8 on 2025-08-05 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduler', '0015_alter_profilemoduler_modulerprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('shop_name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('moduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='togarmoduler', to='moduler.modulerusermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagermanager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NumPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, null=True)),
                ('tager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagerphone', to='togar.tagermodel')),
            ],
        ),
    ]
