# Generated by Django 5.0.8 on 2025-08-06 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduler', '0015_alter_profilemoduler_modulerprofile'),
        ('togar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TagerDof3atModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('dof3a', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dof3attager', to='togar.tagermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertagerdof3at', to=settings.AUTH_USER_MODEL)),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TagerInvoicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('stay', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('Payment', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('barcode', models.ImageField(blank=True, upload_to='images/barcodestager/')),
                ('barcode_id', models.CharField(max_length=13, null=True)),
                ('moduler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduler.modulerusermodel')),
                ('tager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagerinvoice', to='togar.tagermodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertagerinvoice', to=settings.AUTH_USER_MODEL)),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TagerInvoicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('price_buy', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type_quantity', models.CharField(max_length=100, null=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tagerinvoiceitems', to='togar.tagerinvoicmodel')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
