# Generated by Django 5.0.8 on 2025-03-07 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_usermanage_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('namepath', models.CharField(default='', max_length=150)),
                ('imgmoduler', models.ImageField(default='', upload_to='imgmoduler/')),
            ],
        ),
        migrations.CreateModel(
            name='ModulerUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('namepath', models.CharField(default='', max_length=150)),
                ('imgmoduler', models.ImageField(default='', upload_to='imgmoduler/')),
                ('is_finished', models.BooleanField(default=False)),
                ('num_products', models.IntegerField(default=100)),
                ('usermanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usermanage')),
            ],
        ),
    ]
