# Generated by Django 5.0.8 on 2025-03-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulerusermodel',
            name='clients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulerusermodel',
            name='mandob',
            field=models.BooleanField(default=False),
        ),
    ]
