# Generated by Django 5.0.8 on 2025-03-13 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usermanage_start_time'),
        ('moduler', '0002_modulerusermodel_clients_modulerusermodel_mandob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulerusermodel',
            name='usermanage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mymodulers', to='accounts.usermanage'),
        ),
    ]
