# Generated by Django 5.0.8 on 2025-05-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduler', '0003_alter_modulerusermodel_usermanage'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulermodel',
            name='namee',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='modulerusermodel',
            name='namee',
            field=models.CharField(default='', max_length=150),
        ),
    ]
