# Generated by Django 5.0.8 on 2025-07-09 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduler', '0004_modulermodel_namee_modulerusermodel_namee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='profile_pictures/avatar_blank.jpg', upload_to='profile_img/')),
                ('logo_picture', models.ImageField(default='profile_pictures/avatar_blank.jpg', upload_to='logo_pictures/')),
                ('shop_name', models.CharField(max_length=50, null=True)),
                ('dec_name', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('post_code', models.CharField(max_length=6, null=True)),
                ('moduler', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modulerprofile', to='moduler.modulerusermodel')),
            ],
        ),
    ]
