# Generated by Django 5.0.8 on 2025-07-09 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduler', '0005_profilemoduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemoduler',
            name='moduler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulerprofile', to='moduler.modulerusermodel'),
        ),
    ]
