# Generated by Django 5.0.8 on 2025-07-09 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduler', '0006_alter_profilemoduler_moduler'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemoduler',
            old_name='moduler',
            new_name='moduler_prof',
        ),
    ]
