# Generated by Django 5.0.8 on 2025-07-09 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduler', '0007_rename_moduler_profilemoduler_moduler_prof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemoduler',
            old_name='moduler_prof',
            new_name='modulerprofile',
        ),
    ]
