# Generated by Django 5.0.8 on 2025-07-09 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduler', '0008_rename_moduler_prof_profilemoduler_modulerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemoduler',
            name='modulerprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulerprof', to='moduler.modulerusermodel'),
        ),
    ]
