# Generated by Django 5.0.8 on 2025-07-24 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduler', '0011_alter_profilemoduler_modulerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulerusermodel',
            name='namepath',
        ),
        migrations.AlterField(
            model_name='modulerusermodel',
            name='num_products',
            field=models.IntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='profilemoduler',
            name='modulerprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulerprofile', to='moduler.modulerusermodel'),
        ),
    ]
