# Generated by Django 5.0.8 on 2025-07-24 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduler', '0012_remove_modulerusermodel_namepath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemoduler',
            name='modulerprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='modulerprofile', to='moduler.modulerusermodel'),
        ),
    ]
